### ISSUE TITLE
Need command to toggle output fade

### ISSUE THREAD

**Issue by fusionstream** [bitfocus/companion-module-roland-xs84h#1]
With the current command set, there is no way to trigger an output fade. This function allows one to use (in one example), the 2nd and 4th row as a preview bus, and then trigger an "Output Fade" to the PGM bus (1 and 3).

**Comment by josephdadams** [comment]
Those functions don't seem to be listed in the specified protocol provided by Roland. You can toggle the Output Off button on/off but the options to set it to Fade or Freeze, set colors, etc. are not listed. I would recommend either using a preset for this, or contacting Roland to see if perhaps there is an extension of the protocol documentation available.
